### ISSUE TITLE
ffmpeg 4.0 and demo app

### ISSUE THREAD

**Issue by NiekAkerboom** [Khang-NT/ffmpeg-binary-android#11]
Hello,

Thank you a lot for writing and making this code open source.
I've got two queries:
- Are you thinking about updating the prebuilt files to the latest FFmpeg 4.0?
- Any plans to include a form of utility class to make it more straightforward to use the FFmpeg library?

Your Android-Media-Converter project looks great, but I haven't gotten the time to learn Kotlin yet so finding the classes/methods that I need in order to use the binaries is kinda tough.

Thanks a bunch!

**Comment by bolds07** [comment]
I recently discovered this repository, but afak, you dont need to learn kotlin (what is pretty much identical to java) or find any methods to use the ffmpeg

What you need is to deploy the binaries together with your java code and call it through Runtime, like you would do in java normally to invoke any executable on windows or linux...

and to discover which parameters to use or how exactly manage to do what you want you will need to read ffmpeg documentation or ask for help in specific forums...

ffmpeg is pretty much straightforward

**Comment by NiekAkerboom** [comment]
@bolds07 Hey, thanks for the reply :)

I got it all to work recently, including the use of FFmpeg 4.0 and NDK r17.
Should've closed the ticket, will do that now.
