### ISSUE TITLE
Always getting ERROR: opus not found using pkg-config (tried both on mac and Ubuntu )

### ISSUE THREAD

**Issue by HitRoxxx** [Khang-NT/ffmpeg-binary-android#2]
Any suggestion

**Comment by Khang-NT** [comment]
Which Android NDK version you're using? 
Do you compile `libopus` successfully? Then these file should exist under `$PREFIX` path:
```
lib/pkgconfig/opus.pc
lib/libopus.a
lib/libopus.la
```

**Comment by HitRoxxx** [comment]
ndk -15c

**Comment by HitRoxxx** [comment]
yes it compiled successfully

**Comment by Khang-NT** [comment]
Let try to remove this line:
```
--pkg-config=/usr/local/bin/pkg-config
```
Or set this to correct path of `pkg-config` in your system.

**Comment by HitRoxxx** [comment]
no success

**Comment by Khang-NT** [comment]
What did you try? Did you remove `--pkg-config` option? 
If you did it but no success, then please check the path `$PKG_CONFIG_PATH` is pointing to correct `pkg-config` folder.
https://github.com/Khang-NT/ffmpeg-binary-android/blob/master/build_scripts/build_ffmpeg.sh#L154

**Comment by Khang-NT** [comment]
Please checkout this commit: https://github.com/Khang-NT/ffmpeg-binary-android/commit/5040ae0a7c72f776fb6ffc0ed9c6d5b74813eb6a
And then, please correct your `$NDK` path (just remove the suffix "`/`" ): 

Here is the wrong path in your log: `/home/hitro/android-ndk-r15c//platforms/android-16/arch-arm/`
