### ISSUE TITLE
ERROR: libx264 not found

### ISSUE THREAD

**Issue by dotdeveloper** [Khang-NT/ffmpeg-binary-android#3]
Hi, firstly many thanks for great scripts and tutorials.

NDK=15rc
OS=macOS High Siera
We use your script files.

I uncommented x264 line both native-mac and armv7a then,  added build ..sh files --enable-libx264 option for ffmpeg. Its result was native-mac compilation was successful but  armv7a was failed. And then added  
 --disable-opencl \ for  x264 into configure options, it's failed again. Updating to ffmpeg newer version did not change anything.

Could you recommend us anything else?

**Comment by Khang-NT** [comment]
Please checkout this commit: https://github.com/Khang-NT/ffmpeg-binary-android/pull/4/commits/2cce3ffd9a64dc0c78dfc821900d4882b43a72eb

Does it fix? With that changes, I have built it successfully.

**Comment by dotdeveloper** [comment]
Ok. I"ll try.

**Comment by dotdeveloper** [comment]
Thank you so much, it is working now.
