### ISSUE TITLE
Error using ffmpeg arm-v8a with youtube-dl

### ISSUE THREAD

**Issue by KaMyKaSii** [Khang-NT/ffmpeg-binary-android#6]
/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/data/user/0/org.qpython.qpy/files/bin/pip4console.py" && exit
py/files/bin/pip4console.py" && exit    <
Input pip commands, ie: pip install {module}
-->youtube-dl --no-check-certificate https://www.pscp.tv/w/1gqxvpbdDRwGB
[periscope] 1gqxvpbdDRwGB: Downloading JSON metadata
[periscope] 1gqxvpbdDRwGB: Downloading m3u8 information
[periscope] 1gqxvpbdDRwGB: Downloading m3u8 information
[periscope] 1gqxvpbdDRwGB: Downloading m3u8 information
[download] Destination: Бананчик - 🎀 2018-04-06 14_53-1gqxvpbdDRwGB.mp4
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.9.x (GCC) 20150123 (prerelease)
  configuration: --prefix=/Users/khangnt/Desktop/ffmpeg-binary-android/build_scripts/build/arm64-v8a --target-os=linux --arch=arm64 --cross-prefix=/Users/khangnt/Desktop/android-ndk-r15/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android- --enable-cross-compile --sysroot=/Users/khangnt/Desktop/android-ndk-r15/platforms/android-21/arch-arm64/ --pkg-config=/usr/local/bin/pkg-config --pkg-config-flags=--static --enable-pic --enable-small --enable-gpl --disable-shared --enable-static --enable-ffmpeg --disable-ffplay --disable-ffprobe --disable-ffserver --disable-protocols --enable-protocol='file,pipe' --disable-demuxers --disable-muxers --enable-demuxer='aac,avi,dnxhd,flac,flv,gif,h261,h263,h264,image2,matroska,webm,mov,mp3,mp4,mpeg,ogg,srt,wav,webvtt' --enable-muxer='3gp,dnxhd,flac,flv,gif,image2,matroska,webm,mov,mp3,mp4,mpeg,ogg,opus,srt,wav,webvtt,ipod' --disable-encoders --disable-decoders --enable-encoder='aac,dnxhd,flac,flv,gif,libmp3lame,libopus,libshine,libvorbis,mpeg4,png,srt,subrip,webvtt' --enable-decoder='aac,aac_at,aac_fixed,aac_latm,dnxhd,flac,flv,h261,h263,h263i,h263p,h264,vp8,vp9,libopus,libvorbis,mp3,mpeg4,wavpack,png,rawvideo,srt,webvtt' --enable-libshine --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-bsf=aac_adtstoasc --disable-doc
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Unrecognized option 'headers'.
Error splitting the argument list: Option not found

ERROR: ffmpeg exited with code 1
-->

Can you help me? And as another user asked in another issue, could you compile and make available full versions of ffmpeg? I do not have any development skills, so I can not do this myself. Thank you so much for your time and great work!

**Comment by Khang-NT** [comment]
I compiled and published full version here: https://github.com/Khang-NT/ffmpeg-binary-android/releases

**Comment by KaMyKaSii** [comment]
@Khang-NT thank you, but ffmpeg is still without some functions, as you can see below:

`-->youtube-dl --no-check-certificate https://www.pscp.tv/w/1OdJrZoPgzqJX
[periscope] 1OdJrZoPgzqJX: Downloading JSON metadata
[periscope] 1OdJrZoPgzqJX: Downloading m3u8 information
[periscope] 1OdJrZoPgzqJX: Downloading m3u8 information
[periscope] 1OdJrZoPgzqJX: Downloading m3u8 information
[download] Destination: Kyle Vertoch - #Wrestlemania34 #Periscope Live Streaming Reaction to Wrestlemania 34! Let’s GO 2018-04-08 20_30-1OdJrZoPgzqJX.mp4
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.9.x (GCC) 20150123 (prerelease)
  configuration: --prefix=/root/source/build_scripts/build_dir --target-os=linux --arch=arm64 --cross-prefix=/opt/android-ndk-r15c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android- --enable-cross-compile --sysroot=/opt/android-ndk-r15c/platforms/android-21/arch-arm64/ --pkg-config=/usr/bin/pkg-config --pkg-config-flags=--static --enable-pic --enable-small --enable-gpl --enable-nonfree --disable-shared --enable-static --enable-ffmpeg --disable-ffplay --disable-ffprobe --disable-ffserver --enable-libshine --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libfdk-aac --enable-bsf=aac_adtstoasc --disable-doc
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
https://prod-video-us-east-1.periscope.tv/IzyySnWl8jaE6QheQWXw3f54i5XGCT2rqDPjZI76NVxYDNvnwBZjdlT2BH4wvSDvq3CDy-C9vbmRzzH18tj65A/live/us-east-1/lhlsweb.m3u8: Protocol not found
Did you mean file:https://prod-video-us-east-1.periscope.tv/IzyySnWl8jaE6QheQWXw3f54i5XGCT2rqDPjZI76NVxYDNvnwBZjdlT2BH4wvSDvq3CDy-C9vbmRzzH18tj65A/live/us-east-1/lhlsweb.m3u8?


ERROR: ffmpeg exited with code 1
-->`
thank you, but ffmpeg is still without some functions, as you can see below:

`-->youtube-dl --no-check-certificate https://www.pscp.tv/w/1OdJrZoPgzqJX
[periscope] 1OdJrZoPgzqJX: Downloading JSON metadata
[periscope] 1OdJrZoPgzqJX: Downloading m3u8 information
[periscope] 1OdJrZoPgzqJX: Downloading m3u8 information
[periscope] 1OdJrZoPgzqJX: Downloading m3u8 information
[download] Destination: Kyle Vertoch - #Wrestlemania34 #Periscope Live Streaming Reaction to Wrestlemania 34! Let’s GO 2018-04-08 20_30-1OdJrZoPgzqJX.mp4
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.9.x (GCC) 20150123 (prerelease)
  configuration: --prefix=/root/source/build_scripts/build_dir --target-os=linux --arch=arm64 --cross-prefix=/opt/android-ndk-r15c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android- --enable-cross-compile --sysroot=/opt/android-ndk-r15c/platforms/android-21/arch-arm64/ --pkg-config=/usr/bin/pkg-config --pkg-config-flags=--static --enable-pic --enable-small --enable-gpl --enable-nonfree --disable-shared --enable-static --enable-ffmpeg --disable-ffplay --disable-ffprobe --disable-ffserver --enable-libshine --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libfdk-aac --enable-bsf=aac_adtstoasc --disable-doc
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
https://prod-video-us-east-1.periscope.tv/IzyySnWl8jaE6QheQWXw3f54i5XGCT2rqDPjZI76NVxYDNvnwBZjdlT2BH4wvSDvq3CDy-C9vbmRzzH18tj65A/live/us-east-1/lhlsweb.m3u8: Protocol not found
Did you mean file:https://prod-video-us-east-1.periscope.tv/IzyySnWl8jaE6QheQWXw3f54i5XGCT2rqDPjZI76NVxYDNvnwBZjdlT2BH4wvSDvq3CDy-C9vbmRzzH18tj65A/live/us-east-1/lhlsweb.m3u8?


ERROR: ffmpeg exited with code 1
-->`
thank you, but ffmpeg is still without some functions, as you can see below:

`-->youtube-dl --no-check-certificate https://www.pscp.tv/w/1OdJrZoPgzqJX
[periscope] 1OdJrZoPgzqJX: Downloading JSON metadata
[periscope] 1OdJrZoPgzqJX: Downloading m3u8 information
[periscope] 1OdJrZoPgzqJX: Downloading m3u8 information
[periscope] 1OdJrZoPgzqJX: Downloading m3u8 information
[download] Destination: Kyle Vertoch - #Wrestlemania34 #Periscope Live Streaming Reaction to Wrestlemania 34! Let’s GO 2018-04-08 20_30-1OdJrZoPgzqJX.mp4
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.9.x (GCC) 20150123 (prerelease)
  configuration: --prefix=/root/source/build_scripts/build_dir --target-os=linux --arch=arm64 --cross-prefix=/opt/android-ndk-r15c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android- --enable-cross-compile --sysroot=/opt/android-ndk-r15c/platforms/android-21/arch-arm64/ --pkg-config=/usr/bin/pkg-config --pkg-config-flags=--static --enable-pic --enable-small --enable-gpl --enable-nonfree --disable-shared --enable-static --enable-ffmpeg --disable-ffplay --disable-ffprobe --disable-ffserver --enable-libshine --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libfdk-aac --enable-bsf=aac_adtstoasc --disable-doc
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
https://prod-video-us-east-1.periscope.tv/IzyySnWl8jaE6QheQWXw3f54i5XGCT2rqDPjZI76NVxYDNvnwBZjdlT2BH4wvSDvq3CDy-C9vbmRzzH18tj65A/live/us-east-1/lhlsweb.m3u8: Protocol not found
Did you mean file:https://prod-video-us-east-1.periscope.tv/IzyySnWl8jaE6QheQWXw3f54i5XGCT2rqDPjZI76NVxYDNvnwBZjdlT2BH4wvSDvq3CDy-C9vbmRzzH18tj65A/live/us-east-1/lhlsweb.m3u8?


ERROR: ffmpeg exited with code 1
-->`
thank you, but ffmpeg is still without some functions, as you can see below:

`-->youtube-dl --no-check-certificate https://www.pscp.tv/w/1OdJrZoPgzqJX
[periscope] 1OdJrZoPgzqJX: Downloading JSON metadata
[periscope] 1OdJrZoPgzqJX: Downloading m3u8 information
[periscope] 1OdJrZoPgzqJX: Downloading m3u8 information
[periscope] 1OdJrZoPgzqJX: Downloading m3u8 information
[download] Destination: Kyle Vertoch - #Wrestlemania34 #Periscope Live Streaming Reaction to Wrestlemania 34! Let’s GO 2018-04-08 20_30-1OdJrZoPgzqJX.mp4
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.9.x (GCC) 20150123 (prerelease)
  configuration: --prefix=/root/source/build_scripts/build_dir --target-os=linux --arch=arm64 --cross-prefix=/opt/android-ndk-r15c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android- --enable-cross-compile --sysroot=/opt/android-ndk-r15c/platforms/android-21/arch-arm64/ --pkg-config=/usr/bin/pkg-config --pkg-config-flags=--static --enable-pic --enable-small --enable-gpl --enable-nonfree --disable-shared --enable-static --enable-ffmpeg --disable-ffplay --disable-ffprobe --disable-ffserver --enable-libshine --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libfdk-aac --enable-bsf=aac_adtstoasc --disable-doc
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
https://prod-video-us-east-1.periscope.tv/IzyySnWl8jaE6QheQWXw3f54i5XGCT2rqDPjZI76NVxYDNvnwBZjdlT2BH4wvSDvq3CDy-C9vbmRzzH18tj65A/live/us-east-1/lhlsweb.m3u8: Protocol not found
Did you mean file:https://prod-video-us-east-1.periscope.tv/IzyySnWl8jaE6QheQWXw3f54i5XGCT2rqDPjZI76NVxYDNvnwBZjdlT2BH4wvSDvq3CDy-C9vbmRzzH18tj65A/live/us-east-1/lhlsweb.m3u8?


ERROR: ffmpeg exited with code 1
-->`

From what I've seen in some other static builds the full ffmpeg binary is around 27MB, which is not too large to be avoided. If it is possible, a truly complete version would be great. Thank you!

**Comment by Khang-NT** [comment]
I uploaded new binary which support `https` protocol.
